### ISSUE TITLE
User case: Large upload file and frequent disconnects.

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/archivist_ynh#1]
Hi,
Is Archivist good solution when backing up file is near about 25Gb through ssh_rsync and there are frequent disconnects?

**Comment by maniackcrudelis** [comment]
My backup is about 50Go.
If it's a directory, Archivist will split it in small parts (~ 500Mo) and send them.
If you have a disconnection during the copy, the next execution of Archivist will ending the job and remove the incomplete part.
But, in no case you can expect a resume of your copy with rsync.

So, I think Archivist can be a solution. At least, I can say in my case, it works fine. Even with 50Go of datas.

**Comment by anmol26s** [comment]
My real problem is frequent disconnections. The backup from Archivist are working great for local storage. But I want a solution which can resume from where the internet got disconnection. I was thinking of torrents but this is not suited as they are not point to point and tracker could give away identity.

**Comment by maniackcrudelis** [comment]
Did you check other methods than rsync and torrent ? Borg maybe ?
Archivist is able to use another sender if you build a simple script to use a other protocol than rsync.

**Comment by anmol26s** [comment]
>  Borg maybe ?
Borg looks good and there are lot of example scripts to automate backup. I will try it and later try to integrate it in Archivist.
Thanks
