### ISSUE TITLE
Do not create real backup if temp failed

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/archivist_ynh#2]
Hi,

I launched `/opt/yunohost/archivist/archivist.sh` after removing my *Laverna* app, and without editing the conf file (yeah, I should have, I simply forgot). I already made a backup with *archivist*, some weeks ago.

Here is the output:

```bash
>> Make a temporary backup for laverna_backup
Error: App 'laverna' will not be saved
Error: There is nothing to save
rm: cannot remove ‘/home/yunohost.app/archivist/backup/ynh_backup/temp/info.json’: No such file or directory
find: `/home/yunohost.app/archivist/backup/ynh_backup/temp': No such file or directory
>>> This backup is different than the previous one
>>>> Make a real backup for laverna_backup
Error: App 'laverna' will not be saved
Error: There is nothing to save
cp: cannot stat ‘/home/yunohost.backup/archives/laverna_backup.tar.gz’: No such file or directory
cp: cannot stat ‘/home/yunohost.backup/archives/laverna_backup.info.json’: No such file or directory
1.7M /home/yunohost.app/archivist/backup/ynh_backup/laverna_backup.tar.gz
```

If "Make a temporary backup" fails, maybe we should not run "Make a real backup" ?

**Comment by maniackcrudelis** [comment]
Hi nicofrand,

you're right, it should not make a real backup if it fails the temporary one.

It's here https://github.com/maniackcrudelis/archivist/blob/master/archivist.sh#L311
As soon as I can do that, I will add an if here with a return 1.

**Comment by nicofrand** [comment]
Thanks !

BTW, I was wondering why "Make a real backup" was not simply doing a `cp` or `mv` of the temp backup, to be faster ?

**Comment by maniackcrudelis** [comment]
Because, the temporary backup is not compressed, and some files are missing.
This backup is designed only for performing a checksum of all the files.

**Comment by maniackcrudelis** [comment]
Fixed here https://github.com/maniackcrudelis/archivist/commit/6a02856d17275beea0f9dd0c757ee95cdd6255cf

I'll upgrade this package with the next upgrade (incoming)

**Comment by maniackcrudelis** [comment]
Upgraded https://github.com/YunoHost-Apps/archivist_ynh/commit/6ccd8ba2435a7face219e36383409ef40d969a61
Should be ok now.
