### ISSUE TITLE
../apps/archivist/config-panel

### ISSUE THREAD

**Issue by pjpmosteiro** [YunoHost-Apps/archivist_ynh#20]
When I try to open the experimental config panel on apps/archivist/config-panel, the server does not load nothing, keeps on loading.

"host": "Debian 9.11",
    "kernel": "4.9.0-11-amd64",
    "packages": {
        "yunohost": {
            "repo": "stable",
            "version": "3.6.4.6"
        },
        "yunohost-admin": {
            "repo": "stable",
            "version": "3.6.4"
        },
        "moulinette": {
            "repo": "stable",
            "version": "3.6.4.1"
        },
        "ssowat": {
            "repo": "stable",
            "version": "3.6.4"

**Comment by maniackcrudelis** [comment]
I also have that issue, but actually I do have it with any apps with a config-panel.
Maybe that an issue with old json config panel, now that the format has changed.

Meanwhile, you can try the CLI version.
That's on my todo list to changed all my json config panel to toml.
