### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by 6-ril** [YunoHost-Apps/archivist_ynh#39]
Hello, 
I have these messages in my logs :

Erreur : Script de sauvegarde ‘conf_ssh’ inconnu
Erreur : Script de sauvegarde ‘conf_ssowat’ inconnu
Erreur : Script de sauvegarde ‘conf_ynh_firewall’ inconnu
Erreur : Script de sauvegarde ‘conf_xmpp’ inconnu
Erreur : Script de sauvegarde ‘conf_nginx’ inconnu
Erreur : Script de sauvegarde ‘conf_cron’ inconnu
Erreur : Script de sauvegarde ‘conf_ynh_currenthost’ inconnu

Not sure if this is an issue for the core backup.

6ril

**Comment by maniackcrudelis** [comment]
Should be fixed by https://github.com/YunoHost-Apps/archivist_ynh/pull/40
